name: font-familiarity
services:
  web:
    # image: ghcr.io/${{ github.repository }}/freefontfinder:latest
    # image: ghcr.io/timholds/font-familiarity/freefontfinder:latest
    image: ghcr.io/timholds/font-familiarity/freefontfinder:${IMAGE_TAG:-latest}

    build:
      context: .
      dockerfile: Dockerfile
    init: true 
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./model:/app/model
      - ./logs:/app/logs
      - ./templates:/app/templates
      - ./static:/app/static
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/test"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

    

  # nginx:
  #   image: nginx:alpine
  #   restart: always
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./static:/app/static
  #   depends_on:
  #     - web

volumes:
  model-data: