name: font-familiarity
services:
  web:
    # image: ghcr.io/${{ github.repository }}/freefontfinder:latest
    image: ghcr.io/timholds/font-familiarity/freefontfinder:latest
    build:
      context: .
      dockerfile: Dockerfile
    init: true 
    restart: always
    volumes:
      - model-data:/app/model
      - ./logs:/app/logs
      - ./templates:/app/templates
      - ./static:/app/static

    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/test"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    #user: 1000:1000  # Non-root user

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/static
      - /etc/ssl/font.crt:/etc/ssl/font.crt:ro
      - /etc/ssl/font.key:/etc/ssl/font.key:ro
    depends_on:
      - web

volumes:
  model-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/var/www/freefontfinder/model'